name       : nx-libs
version    : 3.5.99.26
release    : 4
source     :
    - https://github.com/ArcticaProject/nx-libs/archive/refs/tags/3.5.99.26.tar.gz : 3ce7ca4e6b57b3a2d7588b2d0f4009036d2566a8925ca2c62f08a8dc0df50357
license    : GPL-2.0-only
component  : network.remote
summary    : NX libraries
description: |
    NX packages needed to setup FreeNX and/or X2Go on a Linux server.
builddeps  :
    - pkgconfig(expat)
    - pkgconfig(fontutil)
    - pkgconfig(libpng)
    - pkgconfig(libjpeg)
    - pkgconfig(libtirpc)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pixman-1)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xdmcp)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xfont2)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcomp)
    - pkgconfig(xpm)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - gccmakedep
    - imake
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-building-with-binutils-2.36.patch
build      : |
    %make CONFIGURE="%configure" PREFIX=/usr LIBDIR=%lidir% IMAKE_DEFINES="-DUseTIRPC=YES"
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -f $installdir/%libdir%/*.a


    # Make xinerama work
    install -dm755 $installdir/%libdir%/nx/X11/Xinerama
    ln -s %libdir%/libX11.so.6 $installdir/%libdir%/nx/X11/Xinerama/libNX_X11.so.6
    ln -s %libdir%/libXext.so.6 $installdir/%libdir%/nx/X11/Xinerama/libNX_Xext.so.6
    ln -s /%libdir%/libNX_Xinerama.so.1 $installdir/%libdir%/nx/X11/Xinerama/libXinerama.so.1
