name       : nx-libs
version    : 3.5.0.32
release    : 1
source     :
    - https://code.x2go.org/releases/source/nx-libs/nx-libs-3.5.0.32-full.tar.gz : be166390ed7c08b96bd62f1e93910d720d105c679481bc389e833003da2a226d
license    : GPL-2.0
component  : network.remote
summary    : NX libraries
description: |
    NX packages needed to setup FreeNX and/or X2Go on a Linux server.
builddeps  :
    - pkgconfig(fontenc)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
build      : |
    %make CONFIGURE="%configure" PREFIX=/usr LIBDIR=%lidir%
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -f $installdir/%libdir%/*.a
    # Make xinerama work. Match lib format of package
    ln -s %libdir%/libX11.so.6 $installdir/usr/lib/nx/X11/Xinerama/libNX_X11.so.6
    ln -s %libdir%/libXext.so.6 $installdir/usr/lib/nx/X11/Xinerama/libNX_Xext.so.6
    ln -s /usr/lib/libNX_Xinerama.so.1 $installdir/usr/lib/nx/X11/Xinerama/libXinerama.so.1
